version: "2"

formatters:
  enable:
    - goimports # checks if the code and import statements are formatted according to the 'goimports' command
    - golines # checks if code is formatted, and fixes long lines

linters:
  enable:
    - asasalint # checks for pass []any as any in variadic func(...any)
    - makezero