// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/infra/grpc/proto/protofiles/hello.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blank) Reset() {
	*x = Blank{}
	mi := &file_internal_infra_grpc_proto_protofiles_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blank) ProtoMessage() {}

func (x *Blank) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_proto_protofiles_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blank.ProtoReflect.Descriptor instead.
func (*Blank) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_proto_protofiles_hello_proto_rawDescGZIP(), []int{0}
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_internal_infra_grpc_proto_protofiles_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_proto_protofiles_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_proto_protofiles_hello_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_infra_grpc_proto_protofiles_hello_proto protoreflect.FileDescriptor

const file_internal_infra_grpc_proto_protofiles_hello_proto_rawDesc = "" +
	"\n" +
	"0internal/infra/grpc/proto/protofiles/hello.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"\a\n" +
	"\x05Blank\")\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2F\n" +
	"\n" +
	"HelloWorld\x128\n" +
	"\x05Hello\x12\t.pb.Blank\x1a\x11.pb.HelloResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/helloB\x1eZ\x1cinternal/infra/grpc/proto/pbb\x06proto3"

var (
	file_internal_infra_grpc_proto_protofiles_hello_proto_rawDescOnce sync.Once
	file_internal_infra_grpc_proto_protofiles_hello_proto_rawDescData []byte
)

func file_internal_infra_grpc_proto_protofiles_hello_proto_rawDescGZIP() []byte {
	file_internal_infra_grpc_proto_protofiles_hello_proto_rawDescOnce.Do(func() {
		file_internal_infra_grpc_proto_protofiles_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infra_grpc_proto_protofiles_hello_proto_rawDesc), len(file_internal_infra_grpc_proto_protofiles_hello_proto_rawDesc)))
	})
	return file_internal_infra_grpc_proto_protofiles_hello_proto_rawDescData
}

var file_internal_infra_grpc_proto_protofiles_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_infra_grpc_proto_protofiles_hello_proto_goTypes = []any{
	(*Blank)(nil),         // 0: pb.Blank
	(*HelloResponse)(nil), // 1: pb.HelloResponse
}
var file_internal_infra_grpc_proto_protofiles_hello_proto_depIdxs = []int32{
	0, // 0: pb.HelloWorld.Hello:input_type -> pb.Blank
	1, // 1: pb.HelloWorld.Hello:output_type -> pb.HelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_infra_grpc_proto_protofiles_hello_proto_init() }
func file_internal_infra_grpc_proto_protofiles_hello_proto_init() {
	if File_internal_infra_grpc_proto_protofiles_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infra_grpc_proto_protofiles_hello_proto_rawDesc), len(file_internal_infra_grpc_proto_protofiles_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infra_grpc_proto_protofiles_hello_proto_goTypes,
		DependencyIndexes: file_internal_infra_grpc_proto_protofiles_hello_proto_depIdxs,
		MessageInfos:      file_internal_infra_grpc_proto_protofiles_hello_proto_msgTypes,
	}.Build()
	File_internal_infra_grpc_proto_protofiles_hello_proto = out.File
	file_internal_infra_grpc_proto_protofiles_hello_proto_goTypes = nil
	file_internal_infra_grpc_proto_protofiles_hello_proto_depIdxs = nil
}
