// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/infra/grpc/proto/protofiles/work.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	mi := &file_internal_infra_grpc_proto_protofiles_work_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_proto_protofiles_work_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_proto_protofiles_work_proto_rawDescGZIP(), []int{0}
}

func (x *WorkRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type WorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkResponse) Reset() {
	*x = WorkResponse{}
	mi := &file_internal_infra_grpc_proto_protofiles_work_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResponse) ProtoMessage() {}

func (x *WorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_proto_protofiles_work_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResponse.ProtoReflect.Descriptor instead.
func (*WorkResponse) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_proto_protofiles_work_proto_rawDescGZIP(), []int{1}
}

func (x *WorkResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_internal_infra_grpc_proto_protofiles_work_proto protoreflect.FileDescriptor

const file_internal_infra_grpc_proto_protofiles_work_proto_rawDesc = "" +
	"\n" +
	"/internal/infra/grpc/proto/protofiles/work.proto\x12\awork_pb\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\":\n" +
	"\vWorkRequest\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\"*\n" +
	"\fWorkResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2S\n" +
	"\x04Work\x12K\n" +
	"\n" +
	"WorkAction\x12\x14.work_pb.WorkRequest\x1a\x15.work_pb.WorkResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/workB\x1eZ\x1cinternal/infra/grpc/proto/pbb\x06proto3"

var (
	file_internal_infra_grpc_proto_protofiles_work_proto_rawDescOnce sync.Once
	file_internal_infra_grpc_proto_protofiles_work_proto_rawDescData []byte
)

func file_internal_infra_grpc_proto_protofiles_work_proto_rawDescGZIP() []byte {
	file_internal_infra_grpc_proto_protofiles_work_proto_rawDescOnce.Do(func() {
		file_internal_infra_grpc_proto_protofiles_work_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infra_grpc_proto_protofiles_work_proto_rawDesc), len(file_internal_infra_grpc_proto_protofiles_work_proto_rawDesc)))
	})
	return file_internal_infra_grpc_proto_protofiles_work_proto_rawDescData
}

var file_internal_infra_grpc_proto_protofiles_work_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_infra_grpc_proto_protofiles_work_proto_goTypes = []any{
	(*WorkRequest)(nil),     // 0: work_pb.WorkRequest
	(*WorkResponse)(nil),    // 1: work_pb.WorkResponse
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_internal_infra_grpc_proto_protofiles_work_proto_depIdxs = []int32{
	2, // 0: work_pb.WorkRequest.data:type_name -> google.protobuf.Struct
	0, // 1: work_pb.Work.WorkAction:input_type -> work_pb.WorkRequest
	1, // 2: work_pb.Work.WorkAction:output_type -> work_pb.WorkResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_infra_grpc_proto_protofiles_work_proto_init() }
func file_internal_infra_grpc_proto_protofiles_work_proto_init() {
	if File_internal_infra_grpc_proto_protofiles_work_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infra_grpc_proto_protofiles_work_proto_rawDesc), len(file_internal_infra_grpc_proto_protofiles_work_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infra_grpc_proto_protofiles_work_proto_goTypes,
		DependencyIndexes: file_internal_infra_grpc_proto_protofiles_work_proto_depIdxs,
		MessageInfos:      file_internal_infra_grpc_proto_protofiles_work_proto_msgTypes,
	}.Build()
	File_internal_infra_grpc_proto_protofiles_work_proto = out.File
	file_internal_infra_grpc_proto_protofiles_work_proto_goTypes = nil
	file_internal_infra_grpc_proto_protofiles_work_proto_depIdxs = nil
}
