// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: internal/infra/grpc/proto/protofiles/work.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkService_WorkAction_FullMethodName  = "/work_pb.WorkService/WorkAction"
	WorkService_GetWorkById_FullMethodName = "/work_pb.WorkService/GetWorkById"
)

// WorkServiceClient is the client API for WorkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkServiceClient interface {
	// main action api, this service apply all routes for processament
	WorkAction(ctx context.Context, in *WorkRequest, opts ...grpc.CallOption) (*ResponseWorkAction, error)
	//Get Work by id
	GetWorkById(ctx context.Context, in *GetWorkByIdInput, opts ...grpc.CallOption) (*Work, error)
}

type workServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkServiceClient(cc grpc.ClientConnInterface) WorkServiceClient {
	return &workServiceClient{cc}
}

func (c *workServiceClient) WorkAction(ctx context.Context, in *WorkRequest, opts ...grpc.CallOption) (*ResponseWorkAction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseWorkAction)
	err := c.cc.Invoke(ctx, WorkService_WorkAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workServiceClient) GetWorkById(ctx context.Context, in *GetWorkByIdInput, opts ...grpc.CallOption) (*Work, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Work)
	err := c.cc.Invoke(ctx, WorkService_GetWorkById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkServiceServer is the server API for WorkService service.
// All implementations must embed UnimplementedWorkServiceServer
// for forward compatibility.
type WorkServiceServer interface {
	// main action api, this service apply all routes for processament
	WorkAction(context.Context, *WorkRequest) (*ResponseWorkAction, error)
	//Get Work by id
	GetWorkById(context.Context, *GetWorkByIdInput) (*Work, error)
	mustEmbedUnimplementedWorkServiceServer()
}

// UnimplementedWorkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkServiceServer struct{}

func (UnimplementedWorkServiceServer) WorkAction(context.Context, *WorkRequest) (*ResponseWorkAction, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkAction not implemented")
}
func (UnimplementedWorkServiceServer) GetWorkById(context.Context, *GetWorkByIdInput) (*Work, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkById not implemented")
}
func (UnimplementedWorkServiceServer) mustEmbedUnimplementedWorkServiceServer() {}
func (UnimplementedWorkServiceServer) testEmbeddedByValue()                     {}

// UnsafeWorkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkServiceServer will
// result in compilation errors.
type UnsafeWorkServiceServer interface {
	mustEmbedUnimplementedWorkServiceServer()
}

func RegisterWorkServiceServer(s grpc.ServiceRegistrar, srv WorkServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkService_ServiceDesc, srv)
}

func _WorkService_WorkAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkServiceServer).WorkAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkService_WorkAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkServiceServer).WorkAction(ctx, req.(*WorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkService_GetWorkById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkByIdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkServiceServer).GetWorkById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkService_GetWorkById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkServiceServer).GetWorkById(ctx, req.(*GetWorkByIdInput))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkService_ServiceDesc is the grpc.ServiceDesc for WorkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "work_pb.WorkService",
	HandlerType: (*WorkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WorkAction",
			Handler:    _WorkService_WorkAction_Handler,
		},
		{
			MethodName: "GetWorkById",
			Handler:    _WorkService_GetWorkById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/infra/grpc/proto/protofiles/work.proto",
}
