services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: work_agent
    ports:
      - "5432:5432"
    networks:
      - appdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d work_agent"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    networks:
      - appdata
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 40s
      timeout: 3s
      retries: 2
      start_period: 50s
    networks:
      - appdata
    depends_on:
      postgres:
        condition: service_healthy 

volumes:
  pgadmin4_data:
  postgres_data:

networks:
  appdata: