services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: work_agent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    depends_on:
      - postgres

  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:8000"
      - "50051:50051"
      - "8080:8080"
    env_file:
    - ../.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 40s
      timeout: 3s
      retries: 2
      start_period: 50s

volumes:
  pgadmin4_data:
  postgres_data: